name: review_bhai_2022
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.13
  equatable: ^2.0.3
  flutter_bloc: ^8.0.1
  firebase: ^9.0.2
  cloud_firestore: ^3.1.13
#  firebase_core: ^1.15.0
  dartz: ^0.10.1
  dio: ^4.0.6
  curl_logger_dio_interceptor: ^0.0.3
  group_radio_button: ^1.2.0
  rflutter_alert: ^2.0.4
  pedantic_mono: ^1.18.0
  intl: ^0.17.0
#  flutter_flipperkit: ^0.0.28
  alice: ^0.2.5
  scroll_app_bar: ^2.0.0
#  firebase_auth: "^0.20.0+1"
#  firebase_core: ^0.7.0
#  url_launcher: ^3.0.0
#  rflutter_alert: ^1.0.3
#  scroll_app_bar: ^1.0.2
#  pedantic: ^1.11.1
#  get_it: ^7.1.3

#  provider: ^4.0.4
#  dartz: ^0.8.9
#  dio: ^3.0.9
#  flutter_bloc: ^6.1.2
#  dio_http_cache: ^0.2.6

#  equatable: ^1.2.4
#  pinput: ^1.0.0

#  flutter_search_bar: ^2.1.0
#  infinite_view_pager: ^1.0.0
#  dots_indicator: ^1.2.0
#  group_radio_button: ^1.0.1
#  flutter_rating_bar: ^3.1.0
#  flutter_svg: ^0.20.0-nullsafety.3
#  persistent_bottom_nav_bar: ^4.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/imgs/
    - assets/icons/

  fonts:
    - family: Constantia
      fonts:
        - asset: assets/fonts/Constantia-constan.ttf

